name: Docker-Testing

on: 
  push:
    branches:
      - '**'
jobs:
  build-website:
    runs-on: node:20.7.0
    steps:
      - name: Test Bash Balloons Rentals Website/WebApp
        run: 
          echo ${{ secrets.GREEN_PEPPER_SPICES }} | base64 -d >> $GITHUB_ENV
          source $GITHUB_ENV
          npm install .
          npm run test
  
  